#include "EditorPch.h"
#include "ProjectBuild.h"

#include "Projects.h"

#include <Lion/Core/Filesystem.h>

using namespace Lion;

namespace ProjectBuild
{
	namespace
	{
		// One project, one GUID: the solution and the project file agree by construction, and nothing else
		// ever references it.
		constexpr const char8* kProjectGuid = "{B27D5FA1-8F5C-4E6B-9C7A-2D51E0C4A9F3}";

		// The headers and the import library beside the editor, assembled by Scripts/PackSdk.bat: one
		// merged include tree (every package keeps to its own subfolder, so one path serves them all) and
		// the lib the module links.
		std::filesystem::path IncludeDirectory()
		{
			return std::filesystem::path(ResourceRootDirectory()) / "Include";
		}

		std::filesystem::path LibraryDirectory()
		{
			return std::filesystem::path(ResourceRootDirectory()) / "Bin";
		}

		// The sources the module is built from: everything the project keeps, except what the build itself
		// writes under Build/ — compiling your own output is how a glob eats its tail.
		void CollectSources(const std::filesystem::path& project,
			std::vector<std::filesystem::path>& compile, std::vector<std::filesystem::path>& include)
		{
			std::error_code error;

			for (std::filesystem::recursive_directory_iterator it(project, error), end; it != end; it.increment(error))
			{
				if (it->is_directory(error))
				{
					if (it->path().filename() == "Build")
						it.disable_recursion_pending();

					continue;
				}

				const std::filesystem::path extension = it->path().extension();

				if (extension == ".cpp")
					compile.push_back(it->path());
				else if (extension == ".h" || extension == ".hpp")
					include.push_back(it->path());
			}
		}
	}

	bool Available()
	{
		std::error_code error;
		return std::filesystem::is_directory(IncludeDirectory(), error)
			&& std::filesystem::exists(LibraryDirectory() / "lion-core.lib", error);
	}

	std::filesystem::path ModulePath(const std::filesystem::path& project)
	{
		return project / "Build" / "Bin" / BuildConfiguration() / kGameModuleFile;
	}

	std::filesystem::path VcxprojPath(const std::filesystem::path& project)
	{
		return project / "Build" / "lion-game.vcxproj";
	}

	bool Generate(const std::filesystem::path& project, std::string& error)
	{
		if (!Available())
		{
			error = "The editor's Include and Bin folders are missing; there is nothing to compile against.";
			return false;
		}

		std::error_code code;
		std::filesystem::create_directories(project / "Build", code);

		if (code)
		{
			error = code.message();
			return false;
		}

		std::vector<std::filesystem::path> compile;
		std::vector<std::filesystem::path> include;
		CollectSources(project, compile, include);

		// The one configuration this editor can load: the module shares the engine's C++ runtime, so it is
		// built the way the engine running it was built — a Debug editor takes a Debug module, an optimised
		// one takes an optimised module, and mixing the two is an allocator dispute inside one process.
		const std::string configuration = BuildConfiguration();
		const bool debug = configuration == "Debug";

		const std::string includes = IncludeDirectory().generic_string() + ";";

		// LN_DISABLE_WARNINGS mirrors the workspace define in premake5.lua — the engine's headers hand it
		// to #pragma warning, and a build without it trips over the bare macro name.
		const std::string defines = std::string("LN_PLATFORM_WIN;LN_DISABLE_WARNINGS=6294 26495 26498 26800;")
			+ (debug ? "LN_DEBUG;_DEBUG" : (configuration == "Shipping" ? "LN_SHIPPING;NDEBUG" : "LN_RELEASE;NDEBUG"));

		// --- The project file, regenerated whole: it is a build description, not a document anyone edits.
		std::ofstream vcxproj(VcxprojPath(project), std::ios::trunc);

		if (!vcxproj.is_open())
		{
			error = "Could not write " + VcxprojPath(project).generic_string() + ".";
			return false;
		}

		vcxproj
			<< "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
			<< "<!-- Generated by the Lion editor before every compile: the file list is a glob of the project. -->\n"
			<< "<Project DefaultTargets=\"Build\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\n"
			<< "  <ItemGroup Label=\"ProjectConfigurations\">\n"
			<< "    <ProjectConfiguration Include=\"" << configuration << "|x64\">\n"
			<< "      <Configuration>" << configuration << "</Configuration>\n"
			<< "      <Platform>x64</Platform>\n"
			<< "    </ProjectConfiguration>\n"
			<< "  </ItemGroup>\n"
			<< "  <PropertyGroup Label=\"Globals\">\n"
			<< "    <ProjectGuid>" << kProjectGuid << "</ProjectGuid>\n"
			<< "    <RootNamespace>Game</RootNamespace>\n"
			<< "  </PropertyGroup>\n"
			<< "  <Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.Default.props\" />\n"
			<< "  <PropertyGroup Label=\"Configuration\">\n"
			<< "    <ConfigurationType>DynamicLibrary</ConfigurationType>\n"
			<< "    <PlatformToolset>v143</PlatformToolset>\n"
			<< "    <CharacterSet>Unicode</CharacterSet>\n"
			<< "    <UseDebugLibraries>" << (debug ? "true" : "false") << "</UseDebugLibraries>\n"
			<< "  </PropertyGroup>\n"
			<< "  <Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.props\" />\n"
			<< "  <PropertyGroup>\n"
			<< "    <OutDir>$(ProjectDir)Bin\\$(Configuration)\\</OutDir>\n"
			<< "    <IntDir>$(ProjectDir)Obj\\$(Configuration)\\</IntDir>\n"
			<< "    <TargetName>lion-game</TargetName>\n"
			<< "  </PropertyGroup>\n"
			<< "  <ItemDefinitionGroup>\n"
			<< "    <ClCompile>\n"
			<< "      <AdditionalIncludeDirectories>" << includes << "%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>\n"
			<< "      <PreprocessorDefinitions>" << defines << ";%(PreprocessorDefinitions)</PreprocessorDefinitions>\n"
			<< "      <LanguageStandard>stdcpp20</LanguageStandard>\n"
			<< "      <RuntimeLibrary>" << (debug ? "MultiThreadedDebugDLL" : "MultiThreadedDLL") << "</RuntimeLibrary>\n"
			<< "      <Optimization>" << (debug ? "Disabled" : "MaxSpeed") << "</Optimization>\n"
			<< "      <DebugInformationFormat>" << (debug ? "ProgramDatabase" : "None") << "</DebugInformationFormat>\n"
			<< "      <AdditionalOptions>/utf-8 %(AdditionalOptions)</AdditionalOptions>\n"
			<< "    </ClCompile>\n"
			<< "    <Link>\n"
			<< "      <AdditionalDependencies>lion-core.lib;%(AdditionalDependencies)</AdditionalDependencies>\n"
			<< "      <AdditionalLibraryDirectories>" << LibraryDirectory().generic_string() << ";%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>\n"
			<< "      <GenerateDebugInformation>" << (debug ? "true" : "false") << "</GenerateDebugInformation>\n"
			<< "    </Link>\n"
			<< "  </ItemDefinitionGroup>\n"
			<< "  <ItemGroup>\n";

		for (const std::filesystem::path& source : compile)
			vcxproj << "    <ClCompile Include=\"" << source.generic_string() << "\" />\n";

		vcxproj << "  </ItemGroup>\n  <ItemGroup>\n";

		for (const std::filesystem::path& header : include)
			vcxproj << "    <ClInclude Include=\"" << header.generic_string() << "\" />\n";

		vcxproj
			<< "  </ItemGroup>\n"
			<< "  <Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.targets\" />\n"
			<< "</Project>\n";

		vcxproj.close();

		// --- The solution, once: it is the door Visual Studio opens the project by, and it never changes.
		const std::filesystem::path solution = project / (Projects::DisplayName(project) + ".sln");

		if (!std::filesystem::exists(solution, code))
		{
			std::ofstream sln(solution, std::ios::trunc);

			sln
				<< "Microsoft Visual Studio Solution File, Format Version 12.00\n"
				<< "# Visual Studio Version 17\n"
				<< "Project(\"{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}\") = \"Game\", \"Build\\lion-game.vcxproj\", \""
				<< kProjectGuid << "\"\n"
				<< "EndProject\n"
				<< "Global\n"
				<< "\tGlobalSection(SolutionConfigurationPlatforms) = preSolution\n"
				<< "\t\t" << configuration << "|x64 = " << configuration << "|x64\n"
				<< "\tEndGlobalSection\n"
				<< "\tGlobalSection(ProjectConfigurationPlatforms) = postSolution\n"
				<< "\t\t" << kProjectGuid << "." << configuration << "|x64.ActiveCfg = " << configuration << "|x64\n"
				<< "\t\t" << kProjectGuid << "." << configuration << "|x64.Build.0 = " << configuration << "|x64\n"
				<< "\tEndGlobalSection\n"
				<< "EndGlobal\n";
		}

		return true;
	}
}
